### ISSUE TITLE
Compatibility with laravel 5.4

### ISSUE THREAD

**Issue by nonsocode** [laravel-notification-channels/twilio#29]
Just want to find out if this package is compatible with laravel 5.4 because i followed the readme instructions to the letter and still didn't get any results.

**Comment by ijin82** [comment]
same for me.

**Comment by carterfort** [comment]
I'm getting this too. As far as I can tell the request is being sent out of the `Twilio/Version/` create() method, but it doesn't seem to actually send the SMS message.

**Comment by phosphore** [comment]
Hey! After some trial and error I made it :+1:
I specifically don't know what the problem was, but I changed in the composer.json:16 the version required for the twilio/sdk `"twilio/sdk": "^5.7.0"`, and run `composer update` in the console.

Also, I had to set my `from` number in the configuration, activating the one offered by Twilio.

**Comment by reganjohnson** [comment]
You can also take a look at my fork which I have been using with the newer SDK and 5.4.

https://github.com/reganjohnson/twilio

**Comment by mfoote** [comment]
@nonsocode I ran into a similar issue, I discovered it was due to not having php5-curl enabled.

**Comment by gregoriohc** [comment]
In the last release (2.0.3) I have updated Twilio SDK to the last version
